#Common Makefile
#Folder defines
ENGINE_FOLDER = Engine/
ENTITY_FOLDER = Entities/

#Include Makefiles
include $(ENGINE_FOLDER)Makefile.engine
include $(ENTITY_FOLDER)Makefile.entities
OBJS =	$(ENGINE_OBJECTS) $(ENTITY_OBJECTS) enDJIN.o
