#Linux
INCLUDES = -I /usr/include/python2.7 -I /usr/include/jsoncpp
TARGET = enDJIN

#Libraries to be linked in.
LIBS = -lsfml-system -lsfml-window -lsfml-graphics  -lsfml-network  -lsfml-audio -lsfgui -ljsoncpp -lssl

#C++ Flags for compiling
CXXFLAGS =	-O2 -g -Wall -fmessage-length=0 -std=c++11 $(INCLUDES)

#Build Target
$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

#Cleaning Target
cleaning:
	rm -f $(OBJS) $(TARGET)
