#Common Makefile
#Folder defines
ENGINE_FOLDER = Engine/
ENTITY_FOLDER = Entities/

#Include Makefiles
include $(ENGINE_FOLDER)Makefile.engine
include $(ENTITY_FOLDER)Makefile.entities
OBJS =	$(ENGINE_OBJS) $(ENTITY_OBJS) enDJIN.o

#Makefile Hacks

#Print variables
print-%:
	@echo '$*=$($*)'

#Banner Macro
banner-%:
	@echo '$* $(ENGINE_NAME)'

