#We're in Windows
INCLUDES = -I c:/MinGW/include -I c:/Python27/include
TARGET =	enDJIN.exe


LIBS = -lsfml-system -lsfml-window -lsfml-graphics  -lsfml-network  -lsfml-audio -lsfgui -ljsoncpp


CXXFLAGS =	-O2 -g -Wall -fmessage-length=0 $(INCLUDES)

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
