#Mac OSX
INCLUDES =
TARGET = enDJIN


LIBS = -lsfml-system -lsfml-window -lsfml-graphics  -lsfml-network  -lsfml-audio -lsfgui -ljsoncpp -lssl


CXXFLAGS =	-O2 -g -Wall -fmessage-length=0 $(INCLUDES)

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
