#Engine Objects
ENGINEOBJECTS = Engine/ConfigParser.o Engine/Game.o Engine/GameScreen.o Engine/KeyMappings.o Engine/Level.o Engine/SplashScreen.o Engine/Tile.o Engine/TileMap.o

#Entity Objects
ACTORS = Entities/Actors/Actor.o Entities/Actors/ActorState.o Entities/Actors/Monster.o Entities/Actors/Player.o
STATICS = Entities/Statics/Item.o
ENTITYOBJECTS = Entities/Entity.o $(ACTORS) $(STATICS) 

OBJS =	$(ENGINEOBJECTS) $(ENTITYOBJECTS) enDJIN.o
