#Entity Makefile

#Folder defines
ACTOR_FOLDER=$(ENTITY_FOLDER)Actors/
STATIC_FOLDER=$(ENTITY_FOLDER)/Statics/

#Include Makefiles
include $(ACTOR_FOLDER)Makefile.actors
include $(STATIC_FOLDER)Makefile.statics 
ENTITY_OBJS=$(ENTITY_FOLDER)Entity.o $(ACTOR_OBJS) $(STATIC_OBJS)
