GAMESCREENS_OBJS = \
	$(GAMESCREENS_FOLDER)GameScreen.o \
	$(GAMESCREENS_FOLDER)GameScreenFactory.o \
	$(GAMESCREENS_FOLDER)SplashScreen.o \
	$(GAMESCREENS_FOLDER)MenuScreen.o \
	$(GAMESCREENS_FOLDER)LoadingScreen.o \
	$(GAMESCREENS_FOLDER)PlayScreen.o
