#Actor Makefile
#Subdirectories
ARMOR_FOLDER=$(ACTOR_FOLDER)ArmorsAttacks/

#Include Makefiles
include $(ARMOR_FOLDER)Makefile.armors

#Actor Objects
ACTOR_OBJS=$(ACTOR_FOLDER)Actor.o $(ACTOR_FOLDER)Monster.o $(ACTOR_FOLDER)MonsterFactory.o $(ACTOR_FOLDER)Player.o $(ARMOR_ATTACK_OBJS)

